import Link from 'next/link';
import { Logo } from '@/components/ui/logo';
import { signOut } from '@/lib/auth/actions';

const navigation = [
  ['/dashboard','Dashboard'], ['/interviews/new','New Interview'], ['/history','Interview History'], ['/analytics','Progress'], ['/profile','Profile'], ['/settings','Settings'], ['/admin','Admin']
];

export function DashboardShell({ children }: { children: React.ReactNode }) {
  return <div className="min-h-screen lg:grid lg:grid-cols-[260px_1fr]"><aside className="desktop-only border-r bg-white p-6"><Logo /><nav aria-label="Dashboard navigation" className="mt-9 space-y-2">{navigation.map(([href,item]) => <Link key={href} href={href} className="block rounded-xl px-4 py-3 text-sm font-semibold text-slate-600 hover:bg-indigo-50 hover:text-indigo-700">{item}</Link>)}</nav><div className="mt-10 rounded-2xl bg-slate-950 p-5 text-white"><p className="text-xs font-bold text-indigo-300">WEEKLY GOAL</p><p className="mt-2 font-bold">3 of 5 sessions</p><div className="mt-3 h-2 rounded-full bg-white/10"><div className="h-2 w-3/5 rounded-full bg-indigo-400" /></div></div></aside><div><header className="flex min-h-18 items-center justify-between border-b bg-white px-5 py-3 lg:px-8"><div className="lg:hidden"><Logo /></div><p className="desktop-only text-sm text-slate-500">Your focused practice workspace</p><div className="flex items-center gap-3"><button aria-label="Notifications" className="grid h-10 w-10 place-items-center rounded-full border">🔔</button><Link aria-label="Open profile" href="/profile" className="grid h-10 w-10 place-items-center rounded-full bg-indigo-600 font-bold text-white">RC</Link><form action={signOut} className="desktop-only"><button className="text-sm font-semibold text-slate-500 hover:text-slate-900">Sign out</button></form></div></header><main id="main-content" className="p-5 pb-24 lg:p-8">{children}</main><nav aria-label="Mobile navigation" className="fixed bottom-0 left-0 right-0 z-20 grid grid-cols-4 border-t bg-white p-2 text-center text-xs font-semibold lg:hidden"><Link className="p-2" href="/dashboard">Home</Link><Link className="p-2" href="/interviews/new">Practice</Link><Link className="p-2" href="/history">History</Link><Link className="p-2" href="/settings">More</Link></nav></div></div>;
}
